version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
